### ISSUE TITLE
router import.js内容能从后端获取嘛？

### ISSUE THREAD

**Issue by xinnicai** [vkcyan/vue-element-asyncLogin#2]
![image](https://user-images.githubusercontent.com/30997380/69293769-dc352000-0c44-11ea-994a-fd7d3be6ab6d.png)
你好，组里要求前端页面的嵌套顺序也从后端获取，可以嘛？

**Comment by BlueDancers** [comment]
不好意思没看到
可以从后台获取的,只要递归生成路由配置文件不出现错误就行
但是import.js里面的不可以从后端获取,这个主要用于获取页面资源的,把每个页面都写上就可以了,保证页面名字可以匹配到对应组件就行了
